-- phpMyAdmin SQL Dump
-- version 4.0.10deb1
-- http://www.phpmyadmin.net
--
-- Хост: localhost
-- Время создания: Июл 13 2016 г., 13:31
-- Версия сервера: 5.5.44-0ubuntu0.14.04.1
-- Версия PHP: 5.5.9-1ubuntu4.17

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8 */;

--
-- База данных: `jsoft`
--

-- --------------------------------------------------------

--
-- Структура таблицы `comment`
--

CREATE TABLE IF NOT EXISTS `comment` (
  `id` smallint(6) NOT NULL AUTO_INCREMENT,
  `user` varchar(20) NOT NULL,
  `note` varchar(250) NOT NULL,
  `ext_id` smallint(6) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `ext_id` (`ext_id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=7 ;

--
-- Дамп данных таблицы `comment`
--

INSERT INTO `comment` (`id`, `user`, `note`, `ext_id`) VALUES
(1, '550', 'test1', 1),
(2, 'jenia', 'test2', 1),
(3, '550', 'beautyful city', 3),
(4, 'Гость', 'круто', 3),
(5, '550', 'test1', 10),
(6, 'jenia', 'test2', 10);

-- --------------------------------------------------------

--
-- Структура таблицы `nasarss`
--

CREATE TABLE IF NOT EXISTS `nasarss` (
  `id` smallint(6) NOT NULL AUTO_INCREMENT,
  `title` varchar(100) NOT NULL,
  `link` varchar(100) NOT NULL,
  `description` varchar(500) NOT NULL,
  `url_image` varchar(200) NOT NULL,
  `url_guid` varchar(200) NOT NULL,
  `pub_date` datetime NOT NULL,
  `upload_date` datetime NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 COMMENT='nasarss' AUTO_INCREMENT=71 ;

--
-- Дамп данных таблицы `nasarss`
--

INSERT INTO `nasarss` (`id`, `title`, `link`, `description`, `url_image`, `url_guid`, `pub_date`, `upload_date`) VALUES
(1, 'Looking Up at New Work Platforms in the Vehicle Assembly Building', 'http://www.nasa.gov/image-feature/looking-up-at-new-work-platforms-in-the-vehicle-assembly-building', 'In this view looking up from the floor of the Vehicle Assembly Building at NASA’s Kennedy Space Center, four levels of new work platforms are now installed on the north and south sides of High Bay 3. The G-level work platforms are the fourth of 10 levels that will surround and provide access to the Space Launch System rocket and Orion spacecraft.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27940134825_a000e40469_o.jpg', 'http://www.nasa.gov/image-feature/looking-up-at-new-work-platforms-in-the-vehicle-assembly-building', '2016-07-13 14:42:00', '2016-07-13 09:07:00'),
(2, 'Researching 3D Printing Technology on the Space Station', 'http://www.nasa.gov/image-feature/researching-3d-printing-technology-on-the-space-station', 'Crew members on the International Space Station re-installed the first 3D printer in orbit, during the week of June 27, 2016, to continue research on the developing technology and how it can be used in space. NASA astronaut Jeff Williams installed the printer in the Microgravity Science Glovebox to begin another round of sample builds.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/iss048e015246.jpg', 'http://www.nasa.gov/image-feature/researching-3d-printing-technology-on-the-space-station', '2016-07-12 14:47:00', '2016-07-13 09:07:00'),
(3, 'Paris at Night', 'http://www.nasa.gov/image-feature/paris-at-night', 'Around local midnight time on April 8, 2015, astronauts aboard the International Space Station took this photograph of Paris, often referred to as the “City of Light.” The pattern of the street grid dominates at night, providing a completely different set of visual features from those visible during the day.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/iss043e093480_lrg.jpg', 'http://www.nasa.gov/image-feature/paris-at-night', '2016-07-11 14:53:00', '2016-07-13 09:07:00'),
(5, 'Expedition 48 Crew Launches to the International Space Station', 'http://www.nasa.gov/image-feature/expedition-48-crew-launches-to-the-international-space-station', 'The Soyuz MS-01 spacecraft launches from the Baikonur Cosmodrome with Expedition 48-49 crewmembers Kate Rubins of NASA, Anatoly Ivanishin of Roscosmos and Takuya Onishi of the Japan Aerospace Exploration Agency (JAXA) onboard, Thursday, July 7, 2016, Kazakh time (July 6 Eastern time), Baikonur, Kazakhstan.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/nhq201607070004.jpg.jpeg', 'http://www.nasa.gov/image-feature/expedition-48-crew-launches-to-the-international-space-station', '2016-07-07 02:03:00', '2016-07-13 09:07:00'),
(6, 'Expedition 48 Soyuz Rollout Test2', 'http://www.nasa.gov/image-feature/expedition-48-soyuz-rollout', 'The Soyuz MS-01 spacecraft is raised vertical after it was rolled out by train to the launch pad at the Baikonur Cosmodrome, Kazakhstan, Monday, July 4, 2016. NASA astronaut Kate Rubins, cosmonaut Anatoly Ivanishin of Roscosmos, and astronaut Takuya Onishi of JAXA will launch to the International Space Station the evening of July 6 Eastern time.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/28080162595_65d5012e24_o.jpg', 'http://www.nasa.gov/image-feature/expedition-48-soyuz-rollout', '2016-07-06 14:20:00', '2016-07-13 09:07:00'),
(7, 'Celebrating Juno''s Arrival at Jupiter', 'http://www.nasa.gov/image-feature/celebrating-junos-arrival-at-jupiter', 'The Juno team celebrates after receiving confirmation from the spacecraft that it had successfully completed the engine burn and entered orbit of Jupiter, Monday, July 4, 2016 in mission control of the Space Flight Operations Facility at the Jet Propulsion Laboratory. The Juno mission launched August 5, 2011 and will orbit the planet for 20 months.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27997163342_4ea08a0abc_o.jpg', 'http://www.nasa.gov/image-feature/celebrating-junos-arrival-at-jupiter', '2016-07-05 15:23:00', '2016-07-13 09:07:00'),
(8, 'Juno Closes in on Jupiter', 'http://www.nasa.gov/image-feature/pia20706/juno-closes-in-on-jupiter', 'This is the final view taken by the JunoCam instrument on NASA''s Juno spacecraft before Juno''s instruments were powered down in preparation for orbit insertion on July 4.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/pia20706_figb_labeled.png', 'http://www.nasa.gov/image-feature/pia20706/juno-closes-in-on-jupiter', '2016-07-04 15:54:00', '2016-07-13 09:07:00'),
(9, 'Counting Down to Juno''s Arrival at Jupiter', 'http://www.nasa.gov/image-feature/counting-down-to-junos-arrival-at-jupiter', 'A model of the Juno spacecraft is seen at a news briefing on Thursday, June 30, 2016, at the Jet Propulsion Laboratory. The Juno mission will arrive at Jupiter July 4, 2016, to orbit the planet for 20 months and collect data on the planetary core, map the magnetic field, and measure the amount of water and ammonia in the atmosphere.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27392354164_7912311d8c_o.jpg', 'http://www.nasa.gov/image-feature/counting-down-to-junos-arrival-at-jupiter', '2016-07-01 14:01:00', '2016-07-13 09:07:00'),
(10, 'Aurora South of Australia test', 'http://www.nasa.gov/image-feature/aurora-south-of-australia', 'On June 24, 2016, Expedition 48 Commander Jeff Williams of NASA photographed the brilliant lights of an aurora from the International Space Station. Sharing the image on social media, Williams wrote, "We were treated to some spectacular aurora south of Australia today."', 'http://www.nasa.gov/sites/default/files/thumbnails/image/iss048e007924.jpg', 'http://www.nasa.gov/image-feature/aurora-south-of-australia', '2016-06-30 15:29:00', '2016-07-13 09:07:00'),
(11, 'Crew Dragon Pressure Vessel Put to the Test', 'http://www.nasa.gov/image-feature/crew-dragon-pressure-vessel-put-to-the-test', 'Pressure vessels built by SpaceX to test its Crew Dragon designs are going through structural testing, so engineers can analyze the spacecraft’s ability to withstand the harsh conditions of launch and spaceflight. A pressure vessel is the area of the spacecraft where astronauts will sit during their ride to the International Space Station.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27263296274_db0774f7be_o.jpg', 'http://www.nasa.gov/image-feature/crew-dragon-pressure-vessel-put-to-the-test', '2016-06-29 14:48:00', '2016-07-13 09:07:00'),
(14, 'A Test Version of the Booster for NASA''s New Rocket', 'http://www.nasa.gov/exploration/systems/sls/multimedia/second-qualification-ground-booster-test-June', 'A test version of the booster for NASA''s new rocket, the Space Launch System, will fire up for the second of two qualification ground tests at 10:05 a.m. EDT (8:05 a.m. MDT) Tuesday, June 28 at prime contractor Orbital ATK''s test facility in Promontory, Utah. NASA Television will air live coverage of the booster test June 28 beginning at 9:30 a.m.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/m16-055a.jpg', 'http://www.nasa.gov/exploration/systems/sls/multimedia/second-qualification-ground-booster-test-June-28', '2016-06-24 13:43:00', '2016-07-13 09:07:00'),
(21, 'Cygnus Cargo Craft Released From Space Station', 'http://www.nasa.gov/image-feature/cygnus-cargo-craft-released-from-space-station', 'Orbital ATK''s Cygnus cargo craft is released from the International Space Station in this June 14, 2016, photograph by ESA astronaut Tim Peake. Once Cygnus reached a safe distance, ground controllers at NASA''s Glenn Research Center initiated the sequence for an experiment design to better understand how fire spreads in a microgravity environment.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27594170151_e2625a7d6b_o.jpg', 'http://www.nasa.gov/image-feature/cygnus-cargo-craft-released-from-space-station', '2016-06-15 14:02:00', '2016-07-13 09:07:00'),
(22, 'Orion Dives Deep for the Sake of Safety', 'http://www.nasa.gov/image-feature/langley/orion-dives-deep-for-the-sake-of-safety', 'A test version of the Orion spacecraft is pulled back like a pendulum and released, taking a dive into the 20-foot-deep (6.1 meters) Hydro Impact Basin at NASA’s Langley Research Center in Hampton, Virginia.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/lrc-2016-h1_p_orion-060712.jpeg', 'http://www.nasa.gov/image-feature/langley/orion-dives-deep-for-the-sake-of-safety', '2016-06-14 12:51:00', '2016-07-13 09:07:00'),
(23, 'NASA Honors Orlando Victims', 'http://www.nasa.gov/image-feature/nasa-honors-orlando-victims', 'The American flag flies at half staff at NASA’s Kennedy Space Center in Florida, with the iconic Vehicle Assembly Building in the background. On Sunday, June 12, President Barack Obama ordered U.S. flags flown at half staff “as a mark of respect for the victims of the act of hatred and terror” at the Pulse nightclub in Orlando.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/ksc-20160613-ph_kls0001_0016.jpeg', 'http://www.nasa.gov/image-feature/nasa-honors-orlando-victims', '2016-06-13 20:55:00', '2016-07-13 09:07:00'),
(24, 'Hubble Uncovers a Mysterious Hermit', 'http://www.nasa.gov/image-feature/goddard/2016/hubble-uncovers-a-mysterious-hermit', 'The drizzle of stars scattered across this image forms a galaxy known as UGC 4879. UGC 4879 is an irregular dwarf galaxy — as the name suggests, galaxies of this type are a little smaller and messier than their cosmic cousins, lacking the majestic swirl of a spiral or the coherence of an elliptical.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/hubble_friday_06102016.jpg', 'http://www.nasa.gov/image-feature/goddard/2016/hubble-uncovers-a-mysterious-hermit', '2016-06-10 13:52:00', '2016-07-13 09:07:00'),
(25, 'Beams of Light on a Golden Lake', 'http://www.nasa.gov/image-feature/beams-of-light-on-a-golden-lake', 'This stunning Earth image taken by the Expedition 47 crew on May 31, 2016, from the International Space Station looks from northwestern China on the bottom into eastern Kazakhstan. The large lake in Kazakhstan with golden sun glint is the crescent-shaped Lake Balkhash, the second largest lake in Central Asia.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27250243350_5563fbc72b_o.jpg', 'http://www.nasa.gov/image-feature/beams-of-light-on-a-golden-lake', '2016-06-09 15:01:00', '2016-07-13 09:07:00'),
(26, 'New Mission Studying Neutron Stars On Track for Launch', 'http://www.nasa.gov/image-feature/new-mission-studying-neutron-stars-on-track-for-launch', 'A view of the Neutron star Interior Composition Explorer (NICER) X-ray Timing Instrument without its protective blanketing shows a collection of 56 close-packed sunshades. NICER, an upcoming NASA astrophysics mission, will uncover the physics governing the ultra-dense interiors of neutron stars.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/image_2_nicer.jpg', 'http://www.nasa.gov/image-feature/new-mission-studying-neutron-stars-on-track-for-launch', '2016-06-08 14:30:00', '2016-07-13 09:07:00'),
(27, 'Frosted Dunes on Mars', 'http://www.nasa.gov/image-feature/frosted-dunes-on-mars', 'Sand dunes cover much of this terrain, which has large boulders lying on flat areas between the dunes. It is late winter in the southern hemisphere of Mars, and these dunes are just getting enough sunlight to start defrosting their seasonal cover of carbon dioxide. Spots form where pressurized carbon dioxide gas escapes to the surface.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27002215442_179da57f4b_o.jpg', 'http://www.nasa.gov/image-feature/frosted-dunes-on-mars', '2016-06-07 15:48:00', '2016-07-13 09:07:00'),
(28, 'Space Station View of Noctilucent Clouds', 'http://www.nasa.gov/image-feature/space-station-view-of-noctilucent-clouds', 'Expedition 47 Flight Engineer Tim Peake of the European Space Agency photographed rare, high-altitude noctilucent or "night shining" clouds from the International Space Station on May 29, 2016. Noctilucent clouds form between 76 to 85 kilometers (47 to 53 miles) above the Earth’s surface, near the boundary of the mesosphere and thermosphere.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27420333805_6fd1876a46_o.jpg', 'http://www.nasa.gov/image-feature/space-station-view-of-noctilucent-clouds', '2016-06-06 14:48:00', '2016-07-13 09:07:00'),
(29, 'Hubble Rocks with a Heavy-Metal Home', 'http://www.nasa.gov/image-feature/goddard/2016/hubble-rocks-with-a-heavy-metal-home', 'This 10.5-billion-year-old globular cluster, NGC 6496, is home to heavy-metal stars of a celestial kind! The stars comprising this spectacular spherical cluster are enriched with much higher proportions of metals — elements heavier than hydrogen and helium are curiously known as metals in astronomy — than stars found in similar clusters.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/hubble_friday_06032016.jpg', 'http://www.nasa.gov/image-feature/goddard/2016/hubble-rocks-with-a-heavy-metal-home', '2016-06-03 12:15:00', '2016-07-13 09:07:00'),
(30, 'The Dark Side of Pluto', 'http://www.nasa.gov/image-feature/the-dark-side-of-pluto', 'NASA’s New Horizons spacecraft took this stunning image of Pluto only a few minutes after closest approach on July 14, 2015. The image was obtained at a high phase angle –that is, with the sun on the other side of Pluto, as viewed by New Horizons. Seen here, sunlight filters through and illuminates Pluto’s complex atmospheric haze layers.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/darksideimage_unann.png', 'http://www.nasa.gov/image-feature/the-dark-side-of-pluto', '2016-06-02 15:29:00', '2016-07-13 09:07:00'),
(31, 'The Little Fox and the Giant Stars', 'http://www.nasa.gov/image-feature/jpl/pia13500/the-little-fox-and-the-giant-stars', 'New stars are the lifeblood of our galaxy, and there is enough material revealed by this Herschel infrared image to build stars for millions of years to come.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/pia13500.jpg', 'http://www.nasa.gov/image-feature/jpl/pia13500/the-little-fox-and-the-giant-stars', '2016-06-01 14:07:00', '2016-07-13 09:07:00'),
(32, 'Great Barrier Reef Near Whitsunday Islands', 'http://www.nasa.gov/image-feature/great-barrier-reef-near-whitsunday-islands', 'An astronaut aboard the International Space Station used a powerful lens to photograph these three reefs in Australia’s Great Barrier Reef on Oct. 12, 2015. Reefs are easy to spot from space because the iridescent blues of shallow lagoons contrast sharply with the dark blues of deep water.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/iss045e056257_lrg.jpg', 'http://www.nasa.gov/image-feature/great-barrier-reef-near-whitsunday-islands', '2016-05-31 15:47:00', '2016-07-13 09:07:00'),
(33, 'Scott Kelly''s Post-Flight Visit to Washington', 'http://www.nasa.gov/image-feature/scott-kellys-post-flight-visit-to-washington', 'Former NASA astronaut Scott Kelly speaks about his historic mission aboard the International Space Station during an event at the United States Capitol Visitor Center, Wednesday, May 25, 2016, in Washington.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27197314521_68a25511c9_o.jpg', 'http://www.nasa.gov/image-feature/scott-kellys-post-flight-visit-to-washington', '2016-05-27 14:34:00', '2016-07-13 09:07:00'),
(34, 'Chasma Boreale and North Polar Ice Cap of Mars', 'http://www.nasa.gov/image-feature/chasma-boreale-and-the-north-polar-ice-cap', 'Mars has bright polar caps of ice that are easily visible from telescopes on Earth. A seasonal cover of carbon-dioxide ice and snow is observed to advance and retreat over the poles during the Martian year. Scientists using radar data have found a record of the most recent Martian ice age recorded in the north polar ice cap.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/mars_polar_deposits_main.jpg', 'http://www.nasa.gov/image-feature/chasma-boreale-and-the-north-polar-ice-cap', '2016-05-26 15:32:00', '2016-07-13 09:07:00'),
(35, 'NASA''s OSIRIS-REx Spacecraft Prepared for Mission to an Asteroid', 'http://www.nasa.gov/image-feature/nasas-osiris-rex-spacecraft-prepared-for-mission-to-an-asteroid', 'NASA''s OSIRIS-REx spacecraft is revealed after its protective cover is removed inside the Payload Hazardous Servicing Facility at Kennedy Space Center, on May 21, 2016. OSIRIS-REx, targeted for a Sept. 8 launch, will be the first U.S. mission to sample an asteroid, retrieve at least two ounces of surface material and return it to Earth for study.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/ksc-20160521-ph_dng0001_0066.jpg', 'http://www.nasa.gov/image-feature/nasas-osiris-rex-spacecraft-prepared-for-mission-to-an-asteroid', '2016-05-25 14:18:00', '2016-07-13 09:07:00'),
(36, 'Fjord and Glacier in East-Central Greenland', 'http://www.nasa.gov/image-feature/fjord-and-glacier-in-east-central-greenland', 'On May 19, 2016, NASA''s IceBridge, an airborne survey of polar ice, crossed Greenland to fly central glacier flowlines in the east-central region of the country. This photo captures the fjord of Violin Glacier, with Nord Glacier at the upper left corner. This is IceBridge''s eighth spring campaign of science flights over Arctic sea and land.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/violinglacier.jpg', 'http://www.nasa.gov/image-feature/fjord-and-glacier-in-east-central-greenland', '2016-05-24 14:33:00', '2016-07-13 09:07:00'),
(37, 'Up and Over', 'http://www.nasa.gov/image-feature/jpl/pia20481/up-and-over', 'Cassini orbited in Saturn''s ring plane -- around the planet''s equator -- for most of 2015.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/pia20481-1041.jpg', 'http://www.nasa.gov/image-feature/jpl/pia20481/up-and-over', '2016-05-23 14:22:00', '2016-07-13 09:07:00'),
(38, 'CubeSats Deployed From the International Space Station', 'http://www.nasa.gov/image-feature/cubesats-deployed-from-the-international-space-station', 'CubeSats fly free after leaving the NanoRacks CubeSat Deployer on the International Space Station on May 17, 2016. Seen here are two Dove satellites. The satellites are part of a constellation designed, built and operated by Planet Labs Inc. to take images of Earth from space.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/26512620163_904c1a34f8_o.jpg', 'http://www.nasa.gov/image-feature/cubesats-deployed-from-the-international-space-station', '2016-05-20 15:21:00', '2016-07-13 09:07:00'),
(39, 'May 19, 2000, Early Morning Liftoff of Atlantis on STS-101 Mission', 'http://www.nasa.gov/image-feature/may-19-2000-early-morning-liftoff-of-atlantis-on-sts-101-mission', 'Flames from the solid rocket boosters lit up the clouds of smoke and steam trailing behind shuttle Atlantis on May 19, 2000, as it lifted off on mission STS-101. It was the shuttle program''s third space station assembly flight, and first space flight for astronaut Jeff Williams, currently aboard the station as a member of the Expedition 47 crew.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/sts101-s-007.jpg', 'http://www.nasa.gov/image-feature/may-19-2000-early-morning-liftoff-of-atlantis-on-sts-101-mission', '2016-05-19 14:06:00', '2016-07-13 09:07:00'),
(40, 'Water Etchings in Western Mexico Sands', 'http://www.nasa.gov/image-feature/water-etchings-in-western-mexico-sands', 'Expedition 47 Commander Tim Kopra of NASA posted this May 15, 2016 photograph to social media, writing, "Water etchings in western @Mexico sands. @Space_Station #Explore"', 'http://www.nasa.gov/sites/default/files/thumbnails/image/iss047e122077a.jpg', 'http://www.nasa.gov/image-feature/water-etchings-in-western-mexico-sands', '2016-05-18 15:02:00', '2016-07-13 09:07:00'),
(41, 'Stargazing From the International Space Station', 'http://www.nasa.gov/image-feature/stargazing-from-the-international-space-station', 'Astronauts aboard the International Space Station (ISS) see the world at night on every orbit — that’s 16 times each crew day. An astronaut took this broad, short-lens photograph of Earth’s night lights while looking out over the remote reaches of the central equatorial Pacific Ocean.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/iss044e045215_lrg.jpg', 'http://www.nasa.gov/image-feature/stargazing-from-the-international-space-station', '2016-05-17 14:43:00', '2016-07-13 09:07:00'),
(42, 'Celebrating Ten Years of NASA''s Consolidated Space Communications Program', 'http://www.nasa.gov/image-feature/celebrating-ten-years-of-nasas-consolidated-space-communications-p', 'This photograph shows NASA’s newest Deep Space Network antenna, Deep Space Station 35 (DSS-35) in Canberra, Australia. The Deep Space Network is managed by the Space Communications and Navigation (SCaN) program office, created on May 16, 2006.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/dss35c.jpg', 'http://www.nasa.gov/image-feature/celebrating-ten-years-of-nasas-consolidated-space-communications-program', '2016-05-16 15:44:00', '2016-07-13 09:07:00'),
(43, 'Hubble Spies a Spiral Snowflake', 'http://www.nasa.gov/image-feature/goddard/2016/hubble-spies-a-spiral-snowflake', 'Together with irregular galaxies, spiral galaxies make up approximately 60 percent of the galaxies in the local universe. However, despite their prevalence, each spiral galaxy is unique — like snowflakes, no two are alike. This is demonstrated by the striking face-on spiral galaxy NGC 6814.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/hubble_friday_05132016.jpg', 'http://www.nasa.gov/image-feature/goddard/2016/hubble-spies-a-spiral-snowflake', '2016-05-13 12:25:00', '2016-07-13 09:07:00'),
(44, 'NASA''s IceBridge Flies Over the Front of a Greenland Glacier', 'http://www.nasa.gov/image-feature/nasas-icebridge-flies-over-the-front-of-a-greenland-glacier', 'Operation IceBridge, NASA''s airborne survey of polar ice, has returned from the Umanaq B mission along Greenland''s western coast. This top-down view from a NOAA P-3 aircraft shows the calving front of Sermeq Kujatdleq glacier. The Naircraft''s #2 lower engine nacelle and left main landing gear fairing is in the foreground at top.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/13173526_1000776189999401_5564117112764344623_o.jpg', 'http://www.nasa.gov/image-feature/nasas-icebridge-flies-over-the-front-of-a-greenland-glacier', '2016-05-12 15:19:00', '2016-07-13 09:07:00'),
(45, 'Full of Science, Dragon Spacecraft Undocks for Return to Earth', 'http://www.nasa.gov/image-feature/full-of-science-dragon-spacecraft-undocks-for-return-to-earth', 'ESA astronaut Tim Peake photographed the SpaceX Dragon cargo craft as it undocked from the International Space Station on May 11, 2016. Scheduled to splashdown in the Pacific Ocean at 2:55 p.m. EDT, the spacecraft will return the final batch of human research samples from former NASA astronaut Scott Kelly’s historic one-year mission.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/26882201861_d4419bc21e_o.jpg', 'http://www.nasa.gov/image-feature/full-of-science-dragon-spacecraft-undocks-for-return-to-earth', '2016-05-11 15:27:00', '2016-07-13 09:07:00'),
(46, 'Smoke From Canadian Wildfires Trapped in Clouds', 'http://www.nasa.gov/image-feature/goddard/2016/smoke-from-canadian-wildfires-trapped-in-clouds', 'NASA''s Aqua satellite captured this image of the clouds over Canada on May 9, 2016.  Entwined within the clouds is the smoke billowing up from the wildfires that are currently burning across a large expanse of the country.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/canada.a2016130.1915.500m_0.jpg', 'http://www.nasa.gov/image-feature/goddard/2016/smoke-from-canadian-wildfires-trapped-in-clouds', '2016-05-10 14:16:00', '2016-07-13 09:07:00'),
(47, 'Mercury Solar Transit', 'http://www.nasa.gov/image-feature/mercury-solar-transit-0', 'The planet Mercury is seen in silhouette, lower third of image, as it transits across the face of the sun Monday, May 9, 2016, as viewed from Boyertown, Pennsylvania. Mercury passes between Earth and the sun only about 13 times a century, with the previous transit taking place in 2006.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/26844814011_363ee0e023_o.jpg', 'http://www.nasa.gov/image-feature/mercury-solar-transit-0', '2016-05-09 15:55:00', '2016-07-13 09:07:00'),
(48, 'Hubble Spies the Barred Spiral Galaxy NGC 4394', 'http://www.nasa.gov/image-feature/goddard/2016/hubble-spies-the-barred-spiral-galaxy-ngc-4394', 'Shown in this Hubble Space Telescope image, NGC 4394 is the archetypal barred spiral galaxy, with bright spiral arms emerging from the ends of a bar that cuts through the galaxy’s central bulge. These arms are peppered with young blue stars, dark filaments of cosmic dust, and bright, fuzzy regions of active star formation.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/hubble_friday_05062016.jpg', 'http://www.nasa.gov/image-feature/goddard/2016/hubble-spies-the-barred-spiral-galaxy-ngc-4394', '2016-05-06 12:00:00', '2016-07-13 09:07:00'),
(49, 'May 5, 1961, Alan Shepard in Spacesuit Before Mercury Launch', 'http://www.nasa.gov/image-feature/may-5-1961-alan-shepard-in-spacesuit-before-mercury-launch', 'Astronaut Alan B. Shepard Jr., in his silver pressure suit with the helmet visor closed, prepares for his Mercury Redstone 3 launch on May 5, 1961. Shepard''s Freedom 7 Mercury capsule lifted off at 9:34 a.m. and flew a suborbital trajectory lasting 15 minutes and 22 seconds. He became the first American to fly into space.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/9460616788_d08d4ae81b_o.jpg', 'http://www.nasa.gov/image-feature/may-5-1961-alan-shepard-in-spacesuit-before-mercury-launch', '2016-05-05 14:31:00', '2016-07-13 09:07:00'),
(50, 'Many Fantastic Colors', 'http://www.nasa.gov/image-feature/many-fantastic-colors', 'The Nili Fossae region, located on the northwest rim of Isidis impact basin, is one of the most colorful regions of Mars. This region is ancient and has had a complicated geologic history, leading to interesting structures like layered bedrock, as well as other compositions.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/esp_044662_2010.jpg', 'http://www.nasa.gov/image-feature/many-fantastic-colors', '2016-05-04 15:35:00', '2016-07-13 09:07:00'),
(51, 'Space Station Flyover of Morocco', 'http://www.nasa.gov/image-feature/space-station-flyover-of-morocco', 'Expedition 47 Flight Engineer Jeff Williams of NASA captured this detailed photograph from the International Space Station during a daytime flyover of Morocco on May 2, 2016. Williams shared the image to social media and asked, "Reptile scales, or incredible and rugged geology in Morocco?"', 'http://www.nasa.gov/sites/default/files/thumbnails/image/13112898_566270633555768_80769708423810417_o.jpg', 'http://www.nasa.gov/image-feature/space-station-flyover-of-morocco', '2016-05-03 15:44:00', '2016-07-13 09:07:00'),
(52, 'The Dew Drop of Saturn', 'http://www.nasa.gov/image-feature/jpl/pia18368/the-dew-drop-of-saturn', 'The water-world Enceladus appears here to sit atop Saturn''s rings like a drop of dew upon a leaf. Even though it appears like a tiny drop before the might of the giant Saturn, Enceladus reminds us that even small worlds hold mysteries and wonders to be explored.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/pia18368-1041.jpg', 'http://www.nasa.gov/image-feature/jpl/pia18368/the-dew-drop-of-saturn', '2016-05-02 14:25:00', '2016-07-13 09:07:00'),
(53, 'James Webb Space Telescope''s Golden Mirror', 'http://www.nasa.gov/image-feature/james-webb-space-telescopes-golden-mirror', 'Inside the clean room at NASA''s Goddard Space Flight Center, the golden James Webb Space Telescope is viewed from overhead with its secondary mirror booms stowed. In the next few months, engineers will install other key elements, and take additional measurements to ensure the telescope is ready for space.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/26602405532_773fcfaf09_o.jpg', 'http://www.nasa.gov/image-feature/james-webb-space-telescopes-golden-mirror', '2016-04-29 14:47:00', '2016-07-13 09:07:00'),
(54, 'Orion Crew Module for Exploration Mission-1 Lifted to Test Stand', 'http://www.nasa.gov/image-feature/orion-crew-module-for-exploration-mission-1-lifted-to-test-stand', 'The Orion spacecraft crew module for Exploration Mission-1 (EM-1) is lifted into a test stand for pressure testing in the Neil Armstrong Operations & Checkout Building at NASA’s Kennedy Space Center. The work is an important milestone on Orion’s journey toward EM-1, its mission beyond the moon atop the Space Launch System rocket in 2018.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/26578355561_bd617abb78_o.jpg', 'http://www.nasa.gov/image-feature/orion-crew-module-for-exploration-mission-1-lifted-to-test-stand', '2016-04-28 15:03:00', '2016-07-13 09:07:00'),
(55, 'Full-Circle Vista from ''Naukluft Plateau'' on Mars', 'http://www.nasa.gov/image-feature/pia20332/full-circle-vista-from-naukluft-plateau-on-mars', 'This mid-afternoon, 360-degree panorama was acquired by the Mast Camera (Mastcam) on NASA''s Curiosity Mars rover on April 4, 2016, as part of long-term campaign to document the context and details of the geology and landforms along Curiosity''s traverse since landing in August 2012.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/pia20332-figa_sol1302_ml_mcam06191_w_labels-cr.jpg', 'http://www.nasa.gov/image-feature/pia20332/full-circle-vista-from-naukluft-plateau-on-mars', '2016-04-27 16:44:00', '2016-07-13 09:07:00'),
(56, 'Light Echoes Used to Study Protoplanetary Disks', 'http://www.nasa.gov/image-feature/light-echoes-used-to-study-protoplanetary-disks', 'This illustration shows a star surrounded by a protoplanetary disk. A new study uses data from NASA''s Spitzer Space Telescope and four ground-based telescopes to determine the distance from a star to the inner rim of its surrounding protoplanetary disk. Researchers used a method called "photo-reverberation," also known as "light echoes.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/pia20645_main.jpg', 'http://www.nasa.gov/image-feature/light-echoes-used-to-study-protoplanetary-disks', '2016-04-26 15:20:00', '2016-07-13 09:07:00'),
(57, 'Ice Scours the North Caspian Sea', 'http://www.nasa.gov/image-feature/ice-scours-the-north-caspian-sea', 'The Operational Land Imager (OLI) on NASA''s Landsat 8 satellite acquired this large natural-color image showing a wide view of the Caspian Sea around the Tyuleniy Archipelago on April 16, 2016. Ocean scientist Norman Kuring of NASA’s Goddard Space Flight Center found a puzzling feature in the image -- lines crisscrossing the North Caspian Sea.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/tyuleniy_oli_2016097_lrg_a.jpg', 'http://www.nasa.gov/image-feature/ice-scours-the-north-caspian-sea', '2016-04-25 15:08:00', '2016-07-13 09:07:00'),
(58, 'Morning Sunglint Over the Pacific', 'http://www.nasa.gov/image-feature/morning-sunglint-over-the-pacific', 'This Earth observation composite image from the International Space Station captures morning sunglint and low clouds over the central Pacific Ocean. The image was put together at the Johnson Space Center in Houston, from a series of photographs taken by Expedition 47 Flight Engineer Jeff Williams on March 25, 2016.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/jsc2016e032858.jpg', 'http://www.nasa.gov/image-feature/morning-sunglint-over-the-pacific', '2016-04-22 15:28:00', '2016-07-13 09:07:00'),
(59, 'Development of High-Power Solar Electric Propulsion', 'http://www.nasa.gov/image-feature/development-of-high-power-solar-electric-propulsion', 'A prototype 13-kilowatt Hall thruster is tested at NASA''s Glenn Research Center in Cleveland. This prototype demonstrated the technology readiness needed for industry to continue the development of high-power solar electric propulsion into a flight-qualified system.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/sep_contract_award_hall_thruster.jpg', 'http://www.nasa.gov/image-feature/development-of-high-power-solar-electric-propulsion', '2016-04-21 12:48:00', '2016-07-13 09:07:00'),
(60, 'Preparing the Vehicle Assembly Building for NASA''s Next Rocket', 'http://www.nasa.gov/image-feature/preparing-the-vehicle-assembly-building-for-nasas-next-rocket', 'A view from below in High Bay 3 inside the Vehicle Assembly Building at NASA’s Kennedy Space Center shows three work platforms installed for NASA’s Space Launch System (SLS) rocket. The platforms will surround and provide access to the SLS rocket and Orion spacecraft for Exploration Mission 1.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/26524351635_5579dbcb71_o.jpg', 'http://www.nasa.gov/image-feature/preparing-the-vehicle-assembly-building-for-nasas-next-rocket', '2016-04-20 15:00:00', '2016-07-13 09:07:00'),
(61, 'Martian Morse Code', 'http://www.nasa.gov/image-feature/martian-morse-code', 'This image of dark dunes on Mars was taken on Feb. 6, 2016, by the HiRISE camera on NASA''s Mars Reconnaissance Orbiter. These dunes are influenced by local topography. The shape and orientation of dunes can usually tell us about wind direction, but in this image, the dune-forms are very complex, so it’s difficult to know the wind direction.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/esp_044675_2580.jpg', 'http://www.nasa.gov/image-feature/martian-morse-code', '2016-07-08 15:10:00', '2016-07-13 09:07:00'),
(62, 'Booster Test for Space Launch System Rocket', 'http://www.nasa.gov/image-feature/booster-test-for-space-launch-system-rocket-1', 'The second and final qualification motor (QM-2) test for the Space Launch System’s booster is seen, Tuesday, June 28, 2016, at Orbital ATK Propulsion Systems test facilities in Promontory, Utah. During the Space Launch System flight the boosters will provide more than 75 percent of the thrust needed to escape the gravitational pull of the Earth.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27928160046_309a2b0123_o.jpg', 'http://www.nasa.gov/image-feature/booster-test-for-space-launch-system-rocket-1', '2016-06-28 17:10:00', '2016-07-13 09:07:00'),
(64, 'NASA''s X-57 Electric Research Plane', 'http://www.nasa.gov/image-feature/nasas-x-57-electric-research-plane', 'With 14 electric motors turning propellers and all of them integrated into a uniquely-designed wing, NASA will test new propulsion technology using an experimental airplane now designated the X-57 and nicknamed “Maxwell.” This concept image illustrates NASA''s X-57 plane in flight.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/sceptor_city_nasa_half_res.jpg', 'http://www.nasa.gov/image-feature/nasas-x-57-electric-research-plane', '2016-06-17 15:43:00', '2016-07-13 09:07:00'),
(65, 'Juno on Jupiter''s Doorstep', 'http://www.nasa.gov/image-feature/juno-on-jupiters-doorstep', 'NASA''s Juno spacecraft obtained this color view on June 21, 2016, at a distance of 6.8 million miles (10.9 million kilometers) from Jupiter. Juno will arrive at Jupiter on July 4. As Juno makes its initial approach, the giant planet''s four largest moons -- Io, Europa, Ganymede and Callisto -- are visible.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/pia20701.jpg', 'http://www.nasa.gov/image-feature/juno-on-jupiters-doorstep', '2016-06-27 14:46:00', '2016-07-13 10:07:00'),
(66, 'Hubble Sees New Dark Spot on Neptune', 'http://www.nasa.gov/image-feature/hubble-sees-new-dark-spot-on-neptune', 'New images obtained on May 16, 2016, by NASA''s Hubble Space Telescope confirm the presence of a dark vortex in the atmosphere of Neptune. This full visible-light image shows that the dark feature resides near and below a patch of bright clouds in the planet''s southern hemisphere.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/hs-2016-22-b-full.jpg', 'http://www.nasa.gov/image-feature/hubble-sees-new-dark-spot-on-neptune', '2016-06-23 15:32:00', '2016-07-13 10:07:00'),
(67, 'Pervasive Ice Retreat in West Antarctica', 'http://www.nasa.gov/image-feature/pervasive-ice-retreat-in-west-antarctica', 'Along the Bellingshausen Sea coast of West Antarctica, ice has been retreating inland being lost to the sea. Scientists knew this, but they lacked a full picture of the scale. Now a team of researchers has compiled a Landsat-based data set and found that such losses have been going on for at least the past four decades.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/antarctica_oli_2015061_lrg.jpg', 'http://www.nasa.gov/image-feature/pervasive-ice-retreat-in-west-antarctica', '2016-06-22 14:57:00', '2016-07-13 10:07:00'),
(68, 'Space Station View of the Full Moon', 'http://www.nasa.gov/image-feature/space-station-view-of-the-full-moon', 'Expedition 48 Commander Jeff Williams of NASA took this photograph on June 21, 2016, from the International Space Station, writing, "A spectacular rise of the full moon just before sunset while flying over western China."', 'http://www.nasa.gov/sites/default/files/thumbnails/image/iss048e004418.jpg', 'http://www.nasa.gov/image-feature/space-station-view-of-the-full-moon', '2016-06-21 14:44:00', '2016-07-13 10:07:00'),
(69, 'Expedition 47 Soyuz Landing', 'http://www.nasa.gov/image-feature/expedition-47-soyuz-landing', 'The Soyuz TMA-19M spacecraft is seen as it lands with Expedition 47 crew members Tim Kopra of NASA, Tim Peake of the European Space Agency, and Yuri Malenchenko of Roscosmos near the town of Zhezkazgan, Kazakhstan on Saturday, June 18, 2016. Kopra, Peake, and Malenchenko are returning after six months onboard the International Space Station.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27490491440_d820b1ecff_o.jpg', 'http://www.nasa.gov/image-feature/expedition-47-soyuz-landing', '2016-06-20 14:10:00', '2016-07-13 10:07:00'),
(70, 'Sunset From the International Space Station', 'http://www.nasa.gov/image-feature/sunset-from-the-international-space-station', 'Expedition 47 Flight Engineer Jeff Williams of NASA captured a series of photos for this composite image of the setting sun reflected by the ocean.', 'http://www.nasa.gov/sites/default/files/thumbnails/image/27041570914_5de6cc0400_o.jpg', 'http://www.nasa.gov/image-feature/sunset-from-the-international-space-station', '2016-06-16 14:17:00', '2016-07-13 10:07:00');

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
